### PR TITLE
Map testing

### PR DESCRIPTION
**Pull request by dentmaged**
@TiTi-418 really wanted this map...

There are a few Cardinal bugs, such as Kits not applied after going through scoreboxes (reported - trying to fix) and the blocks don't fall (need to report that).

### CODE REVIEW

**Comment by dentmaged** [comment]
oh wow

**Comment by CoWinkKeyDinkInc** [comment]
It looks like you haven't properly switched branches on the GitHub application.  Don't worry about it though, I'll be deleting the map testing branch as it's too much to manage.  Pull requests will now be directed to the main fork `master`.

**Comment by twizmwazin** [comment]
Do people actually use the GitHub client for Windows? I would suggest using SmartGit if you need a GUI, although I personally prefer the command line. :)

**Comment by TiTi-418** [comment]
For this repo the GitHub client it's ok, you have a lot of experience.

**Comment by dentmaged** [comment]
I use the command line. But I don't know why that happened.

**Comment by twizmwazin** [comment]
@dentmaged Looks like you had checked out a different branch or something.

**Comment by TiTo-418** [comment]
Added: https://github.com/CoWinkKeyDinkInc/OCN-Maps/commit/76a4de761a2760f24401c1594192b490713ba240
Thanks

**Pull request closed without merging**
